### PR TITLE
Fix error during setup

### PR DESCRIPTION
**Pull request by bmjansen**
Fix this error during setup of SpotWeb using a MySQL database:
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function dbeng_pdo_mysql::connect(), 5 passed in /volume1/web/spotweb/lib/dbeng/dbeng_pdo_mysql.php on line 47 and exactly 6 expected in /volume1/web/spotweb/lib/dbeng/dbeng_pdo_mysql.php:19

### CODE REVIEW

**Comment by Sweepr** [comment]
@bmjansen. strange, i have done quite some installing since last release and i did not see this error, did you @mesa57?

Sidenote: i use MariaDB.

I'll have a look into this PR tomorrow, not much time today.

**Comment by bmjansen** [comment]
It looks like the error has been introduced by commit https://github.com/spotweb/spotweb/commit/b8d2d80b3eb3e8e5bf422a831d696d8d80452a73

**Comment by mesa57** [comment]
@Sweepr : schema was added as parameter, but this function is missing that. The function is only used when setting up spotweb with a mysql root password to create a database / user from then install.php

**Comment by Sweepr** [comment]
@bmjansen Thanks for your contribution, my apologies for missing that one.
